INSERT INTO ALLCODES  values ('ROLE','R1','Admin', N'Quản trị viên',getdate(),getdate() ); 
INSERT INTO ALLCODES  values ('ROLE','R2','Doctor', N'Bác sĩ',getdate(),getdate() ); 
INSERT INTO ALLCODES  values ('ROLE','R3','Patient', N'Bệnh nhân' ,getdate(),getdate()); 					
INSERT INTO ALLCODES  values ('STATUS','S1','New', N'Lịch hẹn mới',getdate(),getdate() ); 
INSERT INTO ALLCODES  values ('STATUS','S2','Confirmed', N'Đã xác nhận',getdate(),getdate() ); 
INSERT INTO ALLCODES  values ('STATUS','S3','Done', N'Đã khám xong',getdate(),getdate() ); 
INSERT INTO ALLCODES  values ('STATUS','S4','Cancel', N'Đã hủy',getdate(),getdate() ); 				
INSERT INTO ALLCODES  values ('TIME','T1','8:00 AM - 9:00 AM', '8:00 - 9:00',getdate(),getdate() ); 
INSERT INTO ALLCODES  values ('TIME','T2','9:00 AM - 10:00 AM', '9:00 - 10:00' ,getdate(),getdate()); 
INSERT INTO ALLCODES  values ('TIME','T3','10:00 AM - 11:00 AM', '10:00 - 11:00',getdate(),getdate() ); 
INSERT INTO ALLCODES  values ('TIME','T4','11:00 AM - 0:00 PM', '11:00 - 12:00',getdate(),getdate() ); 				
INSERT INTO ALLCODES  values ('TIME','T5','1:00 PM - 2:00 PM', '13:00 - 14:00' ,getdate(),getdate()); 
INSERT INTO ALLCODES  values ('TIME','T6','2:00 PM - 3:00 PM', '14:00 - 15:00' ,getdate(),getdate()); 
INSERT INTO ALLCODES  values ('TIME','T7','3:00 PM - 4:00 PM', '15:00 - 16:00',getdate(),getdate() ); 
INSERT INTO ALLCODES  values ('TIME','T8','4:00 PM - 5:00 PM', '16:00 - 17:00',getdate(),getdate() ); 				
INSERT INTO ALLCODES  values ('POSITION','P0','None', N'Bác sĩ',getdate(),getdate() ); 
INSERT INTO ALLCODES  values ('POSITION','P1','Master', N'Thạc sĩ' ,getdate(),getdate()); 
INSERT INTO ALLCODES  values ('POSITION','P2','Doctor', N'Tiến sĩ' ,getdate(),getdate()); 
INSERT INTO ALLCODES  values ('POSITION','P3','Associate Professor', N'Phó giáo sư' ,getdate(),getdate()); 
INSERT INTO ALLCODES  values ('POSITION','P4','Professor', N'Giáo sư' ,getdate(),getdate());
INSERT INTO ALLCODES  values ('GENDER','M','Male', 'Nam' ,getdate(),getdate()); 
INSERT INTO ALLCODES  values ('GENDER','F','Female', N'Nữ' ,getdate(),getdate()); 
INSERT INTO ALLCODES  values ('GENDER','O','Other', N'Khác' ,getdate(),getdate()); 