INSERT INTO ALLCODES  values ('R1','ROLE','Admin', N'Quản trị viên',getdate(),getdate() ); 
INSERT INTO ALLCODES  values ('R2','ROLE','Doctor', N'Bác sĩ',getdate(),getdate() ); 
INSERT INTO ALLCODES  values ('R3','ROLE','Patient', N'Bệnh nhân' ,getdate(),getdate()); 					
INSERT INTO ALLCODES  values ('S1','STATUS','New', N'Lịch hẹn mới',getdate(),getdate() ); 
INSERT INTO ALLCODES  values ('S2','STATUS','Confirmed', N'Đã xác nhận',getdate(),getdate() ); 
INSERT INTO ALLCODES  values ('S3','STATUS','Done', N'Đã khám xong',getdate(),getdate() ); 
INSERT INTO ALLCODES  values ('S4','STATUS','Cancel', N'Đã hủy',getdate(),getdate() ); 				
INSERT INTO ALLCODES  values ('T1','TIME','8:00 AM - 9:00 AM', '8:00 - 9:00',getdate(),getdate() ); 
INSERT INTO ALLCODES  values ('T2','TIME','9:00 AM - 10:00 AM', '9:00 - 10:00' ,getdate(),getdate()); 
INSERT INTO ALLCODES  values ('T3','TIME','10:00 AM - 11:00 AM', '10:00 - 11:00',getdate(),getdate() ); 
INSERT INTO ALLCODES  values ('T4','TIME','11:00 AM - 0:00 PM', '11:00 - 12:00',getdate(),getdate() ); 				
INSERT INTO ALLCODES  values ('T5','TIME','1:00 PM - 2:00 PM', '13:00 - 14:00' ,getdate(),getdate()); 
INSERT INTO ALLCODES  values ('T6','TIME','2:00 PM - 3:00 PM', '14:00 - 15:00' ,getdate(),getdate()); 
INSERT INTO ALLCODES  values ('T7','TIME','3:00 PM - 4:00 PM', '15:00 - 16:00',getdate(),getdate() ); 
INSERT INTO ALLCODES  values ('T8','TIME','4:00 PM - 5:00 PM', '16:00 - 17:00',getdate(),getdate() ); 				
INSERT INTO ALLCODES  values ('P0','POSITION','None', N'Bác sĩ',getdate(),getdate() ); 
INSERT INTO ALLCODES  values ('P1','POSITION','Master', N'Thạc sĩ' ,getdate(),getdate()); 
INSERT INTO ALLCODES  values ('P2','POSITION','Doctor', N'Tiến sĩ' ,getdate(),getdate()); 
INSERT INTO ALLCODES  values ('P3','POSITION','Associate Professor', N'Phó giáo sư' ,getdate(),getdate()); 
INSERT INTO ALLCODES  values ('P4','POSITION','Professor', N'Giáo sư' ,getdate(),getdate());
INSERT INTO ALLCODES  values ('M','GENDER','Male', 'Nam' ,getdate(),getdate()); 
INSERT INTO ALLCODES  values ('F','GENDER','Female', N'Nữ' ,getdate(),getdate()); 
INSERT INTO ALLCODES  values ('O','GENDER','Other', N'Khác' ,getdate(),getdate()); 